### ISSUE TITLE
data8x image build fails with error 500

### ISSUE THREAD

**Issue by felder** [berkeley-dsep-infra/datahub#1347]
```
#!/bin/bash -eo pipefail
if [ "false" == "true" ]; then
  HUBPLOY_ARGS="--check-registry --push"
else
  HUBPLOY_ARGS="--commit-range ${COMMIT_RANGE}"
fi
hubploy build data8x  ${HUBPLOY_ARGS}

Trying to fetch parent image gcr.io/data8x-scratch/data8x-user-image:75f07f8
Traceback (most recent call last):
  File "/root/repo/venv/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/root/repo/venv/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://104.154.82.79:2376/v1.35/images/create?tag=75f07f8&fromImage=gcr.io%2Fdata8x-scratch%2Fdata8x-user-image

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/repo/venv/bin/hubploy", line 11, in <module>
    load_entry_point('hubploy==0.1.0', 'console_scripts', 'hubploy')()
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/__main__.py", line 67, in main
    image.fetch_parent_image()
  File "/root/repo/venv/lib/python3.7/site-packages/hubploy/config.py", line 102, in fetch_parent_image
    self.docker.images.pull(parent_image_spec)
  File "/root/repo/venv/lib/python3.7/site-packages/docker/models/images.py", line 445, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/root/repo/venv/lib/python3.7/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/root/repo/venv/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/root/repo/venv/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by felder** [comment]
@chrispyles was attempting to submit PR #1346 and encountered this problem.

**Comment by yuvipanda** [comment]
Somehow the images were no longer public - we explicitly *do* want them to be public. There seemed to be a newer way to make it public, which I have done. This has fixed the tests!

![Uploading image.png…]()
