### ISSUE TITLE
500: Internal Server Error - on Canvas login

### ISSUE THREAD

**Issue by keithjohnson-berkeley** [berkeley-dsep-infra/datahub#2022]
datahub became unresponsive in browser (Firefox).

I got this error on opening in a different window and authorizing via Canvas 

It looks like this was an issue in April of this year, but was resolved?  I removed cookies, and switched to a different browser (Chrome) but neither move resolved the problem.

thanks & happy holidays.

**Comment by jessiiicamae** [comment]
Hi I am also having this issue in Chrome and Safari, how do I fix this?

**Comment by warrenbaim** [comment]
Same.

**Comment by ryanlovett** [comment]
From the hub logs:
```
Message: 'Exception in callback %r'
Arguments: (functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f42bff29df0>>, <Task finished name='Task-1164753' coro=<JupyterHub.update_last_activity() done, defined at /usr/local/lib/python3.8/dist-packages/jupyterhub/app.py:2528> exception=OperationalError('(sqlite3.OperationalError) database or disk is full')>),)
[I 2020-12-28 06:09:05.805 JupyterHub log:181] 200 GET /hub/metrics (@10.20.18.9) 16.39ms
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    self.flush()
  File "/usr/lib/python3.8/logging/__init__.py", line 1065, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/usr/local/bin/jupyterhub", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2863, in launch_instance
    loop.start()
  File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1705, in _execute
    self.finish()
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 172, in finish
    super().finish(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1160, in finish
    self._log()
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1736, in _log
    self.application.log_request(self)
  File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 2237, in log_request
    self.settings["log_function"](handler)
  File "/usr/local/lib/python3.8/dist-packages/jupyterhub/log.py", line 181, in log_request
    log_method(msg.format(**ns))
Message: '200 GET /hub/metrics (@10.20.18.9) 16.39ms'
Arguments: ()
```

**Comment by ryanlovett** [comment]
/srv/jupyterhub/ was full so I compressed one of its old log files. There is about 5GB free.

datahub should be working again.

**Comment by keithjohnson-berkeley** [comment]
thank you!

**Comment by warrenbaim** [comment]
Thank you!

**Comment by yuvipanda** [comment]
Thanks for taking care of this, @ryanlovett.
