### ISSUE TITLE
Error with jupyter lab build

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/datahub#373]
Upon entering /lab on staging I'm presented with a window
```
Build Recommended
JupyterLab build is suggested:
jupyter-gmaps needs to be included in build
```
I asked it to proceed but then it failed and said to run `jupyter lab build` to see the output. I ran it in a terminal:
```
$ jupyter lab build
[LabBuildApp] > node /srv/app/venv/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.12.3", while you're on "1.6.0".
Done in 13.93s.
[LabBuildApp] > node /srv/app/venv/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at Object.exports.fork (child_process.js:103:10)
    at fork (/srv/app/venv/share/jupyter/lab/staging/node_modules/worker-farm/lib/fork.js:17:36)
    at Farm.startChild (/srv/app/venv/share/jupyter/lab/staging/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/srv/app/venv/share/jupyter/lab/staging/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.addCall (/srv/app/venv/share/jupyter/lab/staging/node_modules/worker-farm/lib/farm.js:307:8)
    at Farm.<anonymous> (/srv/app/venv/share/jupyter/lab/staging/node_modules/worker-farm/lib/farm.js:38:10)
    at _class.boundWorkers (/srv/app/venv/share/jupyter/lab/staging/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (/srv/app/venv/share/jupyter/lab/staging/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at /srv/app/venv/share/jupyter/lab/staging/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:116:11
    at Array.forEach (<anonymous>)
    at _class.runTasks (/srv/app/venv/share/jupyter/lab/staging/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:94:13)
    at UglifyJsPlugin.optimizeFn (/srv/app/venv/share/jupyter/lab/staging/node_modules/uglifyjs-webpack-plugin/dist/index.js:195:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:972:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:968:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:905:27)
    at hooks.make.callAsync.err (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compiler.js:494:17)
    at _done (eval at create (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (/srv/app/venv/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:771:12)
    at processModuleDependencies.err (/srv/app/venv/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:710:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ryanlovett** [comment]
This was based on two commit prior -- CI hadn't completed. Latest is fine.
